<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Messages') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to('/messages') ?>" data-ajax><?= __('Messages') ?></a></li>
            <li class="breadcrumb-item active"><?= $message['title'] ?></li>
        </ol>
    </nav>

    <?= $message['message'] ?>
</div>
