<h1 class="title"><?= $shop['name'] ?> - <?= $q ?></h1>

<ul class="breadcrumber">
    <li><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
    <li><a href="<?= url_to('/shops') ?>" data-ajax><?= __('WebShops') ?></a></li>
    <li><a href="<?= url_to('/shop/' . $shop['slug']) ?>" data-ajax><?= $shop['name'] ?></a></li>
    <li class="active"><?= __(Input::get('q')) ?></li>
</ul>

<div class="shop-categories">
    <?= partial('WebShop.categories', [
        'categories' => $categories,
        'shop' => $shop,
        'q' => $q
    ]) ?>
</div>

<div class="shop-itens">
    <?php foreach ($products as $product): ?>
        <div class="item">
            <div class="name"><?= $product['name'] ?></div>
            <div class="image">
                <img src="<?= util('WebShop.WebShop')->image($product) ?>" />
            </div>
            <div class="info">
                <p><?= __('from %d %s', [$product['price'], config('coins')[$shop['coin']]['name']]) ?></p>
                <p><?= __('%d sold', [$product['solds']]) ?></p>
            </div>
            <div class="buy">
                <a data-ajax href="<?= url_to('/shop/' . $shop['slug'] . '/' . $product['category_slug'] . '/' . $product['slug']) ?>" class="btn"><?= __('+ details') ?></a>
            </div>
        </div>
    <?php endforeach ?>
</div>