<section class="content-header">
    <h1><?= __('Indication goals') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-success btn-sm" href="<?= url_to('/admin/indication/goals/add') ?>"><?= __('Add') ?></a>
    </div>
</section>

<section class="content">
    <?php if (empty($goals)): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No indication goals found') ?></p>
        </div>
    <?php else: ?>
        <div class="box box-default table-responsive">
            <table id="shops-table" class="table table-condensed table-hover table-striped">
                <thead>
                    <tr>
                        <th><?= __('Goal') ?></th>
                        <th width="80"></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($goals as $goal): ?>
                        <tr>
                            <td><?= $goal['goal'] ?></td>
                            <td class="record-actions">
                                <a data-ajax class="btn btn-xs btn-default" href="<?= url_to('/admin/indication/goals/edit/' . $goal['id']) ?>"><?= __('Edit') ?></a>
                                <a data-ajax-delete class="btn btn-danger btn-xs" href="<?= url_to('/admin/indication/goals/delete/' . $goal['id']) ?>"><?= __('Delete') ?></a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</section>
