<h1 class="title"><?= __('All events') ?></h1>

<?php if (count($categories) > 0): ?>
    <select class="margin-bottom" style="width:100%" id="event-category">
        <option value="*"><?= __('All') ?></option>
        <?php foreach ($categories as $category): ?>
            <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
        <?php endforeach ?>
    </select>

    <?php foreach ($categories as $category): ?>
        <div class="events events-<?= $category['id'] ?>"></div>
    <?php endforeach ?>
<?php else: ?>
    <div class="events"></div>
<?php endif ?>