<section class="content-header">
    <h1><?= __('Add new download') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/downloads') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">
    <div class="box box-default">
        <form data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/downloads/add') ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="downloads-name"><?= __('Name') ?> <span class="required">*</span></label>

                    <div class="col-sm-4">
                        <input class="form-control" type="text" name="name" id="downloads-name" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="downloads-size"><?= __('Size') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <input class="form-control" type="text" name="size" id="downloads-size" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="downloads-desc"><?= __('Description') ?></label>

                    <div class="col-sm-10">
                        <textarea class="form-control" name="desc" id="downloads-desc"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="downloads-links"><?= __('Links') ?></label>

                    <div class="col-sm-10 container-add-link">
                        <div class="input-group" style="width:100%">
                            <input class="form-control" style="width:40%;margin-right:2%" type="text" placeholder="<?= __('Name') ?>" name="links[0][name]" />
                            <input class="form-control" style="width:58%" type="text" placeholder="<?= __('Link') ?>" name="links[0][link]" />
                        </div>
                    </div>
                </div>

                <div style="text-align:right;margin-top:-10px">
                    <a class="btn btn-xs btn-success add-link" href="javascript:void(0)"><?= __('Add') ?></a>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px;">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>