<section class="content-header">
    <h1><?= __('Settings plugin Exchange') ?></h1>
</section>

<section class="content">
    <?php if (count($coins) <= 1): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No coins found') ?></p>
        </div>
    <?php else: ?>
        <div class="box box-default">
            <form data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/exchange/config') ?>" method="post">
                <div class="box-body">
                    <table class="table table-condensed table-hover table-striped">
                        <thead>
                            <tr>
                                <th width="10"></th>
                                <th><?= __('Coin') ?></th>
                                <th><?= __('Tax') ?></th>
                                <th width="10" style="text-align:center">%</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($coins as $coin): ?>
                                <tr>
                                    <td style="vertical-align:middle">
                                        <input<?= isset($change[$coin['id']]) ? ' checked' : '' ?> type="checkbox" name="coins[<?= $coin['id'] ?>][active]" value="1" />
                                    </td>
                                    <td style="vertical-align:middle"><?= $coin['name'] ?></td>
                                    <td style="vertical-align:middle">
                                        <input style="width:60px;margin-right:5px;display:inline-block" type="text" value="<?= isset($change[$coin['id']]) && isset($change[$coin['id']]['tax']) ? $change[$coin['id']]['tax'] : '' ?>" name="coins[<?= $coin['id'] ?>][tax]" class="form-control" />%
                                    </td>
                                    <td style="white-space:nowrap;text-align:center">
                                        <table>
                                            <tbody>
                                                <tr>
                                                    <?php foreach ($coins as $c): ?>
                                                        <?php if ($c['id'] === $coin['id']) continue ?>
                                                        <td>
                                                            <?= $c['name'] ?><br />
                                                            <input style="width:60px;margin-right:5px" type="text" value="<?= isset($change[$coin['id']]) && isset($change[$coin['id']]['rates'][$c['id']]) ? $change[$coin['id']]['rates'][$c['id']] : '' ?>" name="coins[<?= $coin['id'] ?>][rates][<?= $c['id'] ?>]" class="form-control" />
                                                        </td>
                                                    <?php endforeach ?>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>

                <div class="box-footer">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </form>
        </div>
    <?php endif ?>
</section>