<h2 class="title"><?= __('My purchases in webshop') ?></h2>
<table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
    <tr>
        <th><?= __('Item') ?></th>
        <th><?= __('Bought at') ?></th>
        <th width="10"></th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($items as $item): ?>
        <tr>
            <td><?= util('Item')->getFullName($item['item']) ?></td>
            <td><?= util('Date')->dateTime($item['create_date']) ?></td>
            <td>
                <?php if (!$item['in_market']
                    && $item['recoverable']): ?>
                    <a data-ajax-action href="<?= url_to('/shop/purchases/recover-item/' . $item['id']) ?>"><?= __('Recover') ?></a>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>