<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= $box['name'] ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to('/lootboxes') ?>" data-ajax><?= __('Loot boxes') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to('/lootboxes/' . $box['id']) ?>" data-ajax><?= $box['name'] ?></a></li>
            <li class="breadcrumb-item active"><?= __('Send gift') ?></li>
        </ol>
    </nav>


    <div class="box-panel">
        <form data-ajax action="<?= url_to('/lootboxes/gift/' . $box['id']) ?>" class="form" method="post">
            <?= function_exists('csrf_field') ? csrf_field() : '' ?>

            <div class="form-group">
                <label class="form-control-label" for="account"><?= __('Account') ?> <span class="required">*</span></label>
                <input class="form-control" type="text" id="account" name="account" maxlength="10" style="width:100%" />
            </div>
            <div class="submit">
                <input type="submit" class="btn btn-info" value="<?= __('Send') ?>">
            </div>
        </form>
    </div>
</div>