<section class="content-header">
    <h1><?= __('Auction plugin settings') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= admin_url_to('/auctions') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">
    <div class="box box-default">
        <form data-ajax class="form-focus" action="<?= admin_url_to('/auctions/config') ?>" method="post">
            <?= function_exists('csrf_field') ? csrf_field() : '' ?>

            <div class="box-body">
                <div class="section">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                            <h5><?= __('Time') ?></h5>
                        </div>

                        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="control-label" for="close_time"><?= __('Time to delivery') ?></label>
                                        <input class="form-control" type="text" value="<?= config('auction.close_time', 60) ?>" name="close_time" id="close-time" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="section">
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                            <h5><?= __('Pusher API') ?></h5>
                        </div>

                        <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                            <div class="form-group">
                                <label class="control-label" for="auth-key"><?= __('Auth key') ?></label>
                                <input class="form-control" type="text" value="<?= config('auction.pusher.auth_key') ?>" name="auth_key" id="auth-key" />
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="secret-key"><?= __('Secret key') ?></label>
                                <input class="form-control" type="text" value="<?= config('auction.pusher.secret_key') ?>" name="secret_key" id="secret-key" />
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="app-id"><?= __('App ID') ?></label>
                                <input class="form-control" type="text" value="<?= config('auction.pusher.app_id') ?>" name="app_id" id="app-id" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="row">
                    <div class="col-sm-offset-3" style="padding-left:15px">
                        <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>