<section class="content-header">
    <h1><?= __('Edit auction') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= admin_url_to('/auctions') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#"><?= __('Auction') ?></a></li>
            <li><a data-ajax href="<?= admin_url_to('/auctions/items?auction_id=' . $auction['id']) ?>"><?= __('Items') ?></a></li>
        </ul>
        <div class="tab-content" style="padding:0">
            <form data-ajax class="form-focus" action="<?= admin_url_to('/auctions/edit/' . $auction['id']) ?>" method="post">
                <?= function_exists('csrf_field') ? csrf_field() : '' ?>

                <div class="box-body">
                    <div class="section">
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                                <h5><?= __('Auction') ?></h5>
                            </div>

                            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="form-group">
                                            <label class="control-label" for="name"><?= __('Name') ?> <span class="required">*</span></label>
                                            <input class="form-control" value="<?= $auction['name'] ?>" type="text" name="name" id="name" />
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label class="control-label" for="active"><?= __('Active') ?></label>
                                            <div>
                                                <input class="form-control toggle"<?= $auction['active'] ? ' checked' : '' ?> type="checkbox" id="active" value="1" name="active" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label" for="start-date"><?= __('Start date') ?></label>
                                            <input data-show-calendar class="form-control" value="<?= util('Date')->date($auction['start_date']) ?>" autocomplete="off" type="text" name="start_date" id="start-date" />
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label" for="end-date"><?= __('End date') ?></label>
                                            <input data-show-calendar class="form-control" value="<?= util('Date')->date($auction['end_date']) ?>" autocomplete="off" type="text" name="end_date" id="end-date" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <div class="row">
                        <div class="col-sm-offset-3" style="padding-left:15px">
                            <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>