<section class="content-header">
    <h1><?= __('Edit auction') ?></h1>
</section>

<section class="content">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#"><?= __('Auction') ?></a></li>
            <li><a data-ajax href="/admin/auctions/items?auction_id=<?= $auction['id'] ?>"><?= __('Items') ?></a></li>
        </ul>
        <div class="tab-content">
            <form class="form-horizontal ajax-form" method="post" action="/admin/auctions/edit/<?= $auction['id'] ?>">
                
                <div class="form-group">
                    <label class="col-sm-2 control-label">Ativo?</label>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="hidden" name="active" value="0">
                                <input type="checkbox" name="active" value="1" <?= $auction['active'] ? 'checked' : '' ?>>
                                Sim
                            </label>
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary"><?= __('Salvar') ?></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>