<section class="content-header">
    <h1><?= __('Settings plugin perfil') ?></h1>
</section>

<section class="content">

    <div class="box box-default">
        <form data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/perfil/config') ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="show-equipments"><?= __('Show equipments') ?></label>

                    <div class="col-sm-10" style="padding-top:5px">
                        <input class="form-control" type="checkbox"<?= config('perfil.show_equipments', true) ? ' checked' : '' ?> id="show-equipments" value="1" name="show_equipments" />
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>