<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title"><?= __("Events") ?></h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div style="padding: 10px 20px;">
                <div class="m-b-30">
                    <a href="/admin/events/add" class="btn btn-success waves-effect waves-light"><i class="fa fa-plus"></i> <?= __("Add new event") ?></a>
                    <a href="/admin/events/categories" class="btn btn-info waves-effect waves-light"><i class="fa fa-tags"></i> Categorias</a>
                </div>

                <div class="table-responsive">
                    <table class="table table-hover mails m-0 table table-actions-bar">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th><?= __("Name") ?></th>
                                <th>Categoria</th>
                                <th>Status</th>
                                <th style="min-width: 170px; text-align: right;"><?= __("Actions") ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($events)): ?>
                                <tr><td colspan="5" class="text-center"><?= __("No events found") ?></td></tr>
                            <?php else: ?>
                                <?php foreach ($events as $event): ?>
                                    <tr>
                                        <td><?= $event["id"] ?></td>
                                        <td><strong><?= $event["name"] ?></strong></td>
                                        <td><span class="label label-default"><?= $event["category_name"] ?></span></td>
                                        <td>
                                            <?php if ($event["active"]): ?><span class="label label-success"><?= __("Active") ?></span><?php else: ?><span class="label label-danger"><?= __("Deactivate") ?></span><?php endif; ?>
                                        </td>
                                        <td class="text-right">
                                            <a href="/admin/events/edit/<?= $event["id"] ?>" class="btn btn-sm btn-primary waves-effect waves-light"><i class="fa fa-pencil"></i> Editar</a>
                                            <a href="/admin/events/delete/<?= $event["id"] ?>" class="btn btn-sm btn-danger waves-effect waves-light delete-button"><i class="fa fa-trash"></i> Excluir</a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>