<h1 class="title"><?= __('Vip advantages') ?></h1>

<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
        <li class="breadcrumb-item"><a href="<?= url_to('/vip') ?>" data-ajax><?= __('Vip') ?></a></li>
        <li class="breadcrumb-item active"><?= __('Advantages') ?></li>
    </ol>
</nav>

<div class="text-center">
    <a data-ajax class="btn bg-orange" href="<?= url_to('/vip') ?>">Resumo</a>
    <a data-ajax class="btn bg-orange" href="<?= url_to('/vip/advantages') ?>">Vantagens</a>
    <!--<a data-ajax class="btn bg-orange" href="<?= url_to('/vip/payment') ?>">Formas de pagamento</a>-->
    <a data-ajax class="btn bg-orange" href="<?= url_to('/packages') ?>">Pacotes</a>
</div>

<hr />

<h3>Vantagens de ser VIP</h3>


<!--<h4>Painel de Usuário <sup>( Minha conta )</sup></h4>

<table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Opções do painel</th>
            <th class="text-center"><b>FREE</b></th> 
			<th class="text-center"><b>VIP PRATA</b></th>			
            <th class="text-center"><b>VIP GOLD</b></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            
										<td class="true">Alterar senha</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>	
        </tr>
        <tr>
										<td>Alterar PID</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>	
        </tr>
        <tr>
            <td class="true">Ultimas Conexões</td>

										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>	
               </tr>
    </tbody>
</table>

<hr />

<h4>Painel de Usuário <sup>( Meus personagens )</sup></h4>

<table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Opções do painel</th>
            <th class="text-center"><b>FREE</b></th>
            <th class="text-center"><b>VIP PRATA</b></th>
            <th class="text-center"><b>VIP GOLD</b></th>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td>Alterar nick</td>

										<td align="center" style="color:#FF2626;">Não</td>
										<td align="center" style="color:#FF2626;">Não</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>	
        </tr>
        <tr>
         <td class="true">Redistribuir Master Skill</td>

										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>	
        </tr>
        <tr>
           <td class="true">Rebuild Stats</td>

										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>
										<td class="true" align="center" style="color:#2DB200;">Sim</td>	
        </tr>
        <tr>
            <td class="true">Trocar de classe</td>

            <td class="true" align="center" style="color:#FF2626;">Não</td>
			 <td class="true" align="center" style="color:#FF2626;">Não</td>
            <td class="true" align="center" style="color:#FF2626;">Não</td>
        </tr>
        <tr>
            	 <td class="true">Transferir Resets</td>

            <td class="true" align="center" style="color:#FF2626;">Não</td>
			 <td class="true" align="center" style="color:#FF2626;">Não</td>
            <td class="true" align="center" style="color:#2DB200;">Sim</td>  
        </tr>
        <tr>
            	<td class="true">Limpar PK</td>

            <td class="true" align="center" style="color:#2DB200;">Sim</td>
			 <td class="true" align="center" style="color:#2DB200;">Sim</td>
            <td class="true" align="center" style="color:#2DB200;">Sim</td>  
        </tr>
        <tr>
          <td class="true">Evoluir</td>

             <td class="true" align="center" style="color:#FF2626;">Não</td>
			     <td class="true" align="center" style="color:#FF2626;">Não</td>
            <td class="true" align="center" style="color:#FF2626;">Não</td>   
        </tr>
    </tbody>
</table>-->

<hr />

<h4>Configuração do Servidor <sup>( Vantagens )</sup></h4>

<table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Configurações</th>
            <th class="text-center"><b>Free</b></th>            
            <th class="text-center"><b>VIP Gold</b></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="true">Sala VIP</td>
            <td class="true" align="center">Não</td>
            <td class="true" align="center">Sim</td>            
        </tr>
        <tr>
			 <td class="true">Atacar automaticamente</td>
            <td class="true" align="center">Não</td>
            <td class="true" align="center">Sim</td>            
        </tr>
        <tr>   
					 <td class="true">Coletar Zen e Itens automaticamente</td>
            <td class="true" align="center">Não</td>
            <td class="true" align="center">Sim</td>            
        </tr>
        <tr>   
            <td class="true">Troca de Nick</td>
            <td class="true" align="center">Não</td>
            <td class="true" align="center">Sim</td>          
        </tr>
    </tbody>
</table>

<hr />

<h4>Chaos Machine <sup>( Vantagens )</sup></h4>

<table class="table table-sm table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Configurações</th>
            <th class="text-center"><b>FREE</b></th>
            <th class="text-center"><b>VIP Gold</b></th>           
        </tr>
    </thead>
    <tbody>
        <tr>
           <td class="true">Combinação item + 10</td>

            <td class="true" align="center">55%</td>

            <td class="true" align="center">65%</td>          

        </tr>
        <tr>           
          <td class="true">Combinação item + 11</td>

            <td class="true" align="center">45%</td>

            <td class="true" align="center">55%</td>
          
			</tr>
        <tr>           
           <td class="true">Combinação item + 12</td>

            <td class="true" align="center">40%</td>

            <td class="true" align="center">50%</td>
            
        </tr>
        <tr>           
          <td class="true">Combinação item + 13</td>

            <td class="true" align="center">35%</td>

            <td class="true" align="center">45%</td>
           
			</tr>
        <tr>    

			  <td class="true">Chaos Item</td>

            <td class="true" align="center">60%</td>

            <td class="true" align="center">75%</td>
            
			</tr>
        <tr>  

         <td class="true">Wing lvl 1</td>

            <td class="true" align="center">35%</td>

            <td class="true" align="center">50%</td>
            
			</tr>
        <tr>           
        <td class="true">Wing lvl 2</td>

            <td class="true" align="center">20%</td>

            <td class="true" align="center">35%</td>
            
			</tr>
        <tr>    
		
			 <td class="true">Pet</td>

            <td class="true" align="center">50%</td>

            <td class="true" align="center">65%</td>
           

			</tr>
        <tr>      
		
		 <td class="true">Dinorant</td>

            <td class="true" align="center">50%</td>

            <td class="true" align="center">65%</td>
           

			</tr>
        <tr>
		
		 <td class="true">Piece Horn</td>

            <td class="true" align="center">60%</td>

            <td class="true" align="center">70%</td>
           

			</tr>
        <tr>   
       
         <td class="true">Broken Horn</td>

            <td class="true" align="center">40%</td>

            <td class="true" align="center">50%</td>
           

			</tr>
        <tr>           
         <td class="true">Criação de Fenrir</td>

            <td class="true" align="center">20%</td>

            <td class="true" align="center">30%</td>
           
			</tr>
        <tr>           
         <td class="true">Upgrade Fenrir</td>

            <td class="true" align="center">20%</td>

            <td class="true" align="center">30%</td>
           
        </tr>
		<tr>   
		
		 <td class="true">Convites</td>

            <td class="true" align="center">60%</td>

            <td class="true" align="center">80%</td>
           
        </tr>
       
    </tbody>
</table>
<hr />