<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?= __('Changelog') ?></h3>
</div>

<div style="margin:10px">
<?php foreach ($versions as $version): ?>
    <div class="box box-default" style="margin-bottom:10px">
        <div class="box-header">
            <h4><?= $version['version'] ?></h4>
        </div>
        <div class="box-body">
            <?= nl2br($version['changelist']) ?>
        </div>
    </div>
<?php endforeach ?>
</div>