import xml.etree.ElementTree as ET

path = r"c:\Users\JUNIOR-DEV\Downloads\MuServer-20260803T155926Z-1-001\Mudream.online\Data\Local\xml\QuestSystem\QuestSystemText.xml"
out = r"c:\Users\JUNIOR-DEV\Downloads\MuServer-20260803T155926Z-1-001\OpenMU\src\GameLogic\QuestPanel\QuestPanelCatalog.Generated.cs"

tree = ET.parse(path)
quests = tree.getroot().findall("Quest")

# After Spider + Bull Fighter, cycle other Lorencia mobs.
MONSTERS_ROTATION = [
    (3, "Spider"),
    (0, "Bull Fighter"),
    (1, "Hound"),
    (2, "Budge Dragon"),
    (4, "Elite Bull Fighter"),
    (6, "Lich"),
    (7, "Giant"),
    (14, "Skeleton"),
]

KUNDUN_MILESTONES = {
    105: (1, 10),
    115: (1, 10),
    125: (1, 11),
    145: (1, 11),
    200: (1, 12),
}
TCA_QUEST_ID = 200
KILL_STEP = 500


def required_kills(index: int) -> int:
    if index <= 1:
        return 3000
    return 3000 + (index - 1) * KILL_STEP


def monster_for(index: int) -> tuple[int, str]:
    if index == 0:
        return 3, "Spider"
    if index == 1:
        return 0, "Bull Fighter"
    return MONSTERS_ROTATION[index % len(MONSTERS_ROTATION)]


lines = [
    "// <auto-generated />",
    "namespace MUnique.OpenMU.GameLogic.QuestPanel;",
    "",
    "public static partial class QuestPanelCatalog",
    "{",
    "    private static QuestPanelDefinition[] BuildQuests() =>",
    "    [",
]

for i, q in enumerate(quests):
    quest_id = i + 1
    title = q.get("Title", f"Quest {quest_id}")
    title = title.replace('"', '\\"').replace("\u2019", "'").replace("\u2018", "'")
    mn, ml = monster_for(i)
    kills = required_kills(i)

    exp = 100_000 + i * 800_000
    money = 50_000 + i * 700_000
    points = 5 + i  # Q1=5, Q2=6, Q3=7 ...
    kundun_count, kundun_level = KUNDUN_MILESTONES.get(quest_id, (0, 0))
    tca_count = 1 if quest_id == TCA_QUEST_ID else 0

    lines.append(
        f"        new({i}, \"{title}\", \"{ml}\", {mn}, {kills}, "
        f"{exp}, {money}, {points}, {kundun_count}, {kundun_level}, {tca_count}),"
    )

lines.extend(["    ];", "}"])

with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {len(quests)} quests")
print(f"Q1 kills={required_kills(0)} {monster_for(0)[1]}")
print(f"Q2 kills={required_kills(1)} {monster_for(1)[1]}")
print(f"Q202 kills={required_kills(len(quests)-1)}")
