# Generates MuMain MudreamCosmeticCatalog.Generated.cpp from catalog + model map.
# Run after import_mudream_cosmetics.ps1 (or standalone if JSON maps exist).
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$modelsPath = Join-Path $PSScriptRoot 'mudream_cosmetic_models.json'
$catalogPath = Join-Path $PSScriptRoot 'mudream_cosmetic_catalog.json'
if (-not (Test-Path $modelsPath)) { throw "Missing $modelsPath - run model mapping first." }
if (-not (Test-Path $catalogPath)) { throw "Missing $catalogPath - run import_mudream_cosmetics_catalog.ps1 first." }

$catalog = Get-Content $catalogPath -Raw | ConvertFrom-Json
$models = Get-Content $modelsPath -Raw | ConvertFrom-Json

function Get-Slot([int]$g, [string]$name) {
    # Equipment slot index (NOT item group). Matches MuMain EQUIPMENT_* constants.
    switch ($g) {
        { $_ -in 0,1,2,3,5 } { return 0 }
        # Group 4 is split by hand: bows go to the shield slot like the vanilla ones,
        # crossbows are held in the weapon hand the way a sword is.
        4 { if ($name -match 'crossbow') { return 0 } else { return 1 } }
        6 { return 1 }
        7 { return 2 }
        8 { return 3 }
        9 { return 4 }
        10 { return 5 }
        11 { return 6 }
        12 { return 7 }
        13 { return 8 }
        default { return 255 }
    }
}
function Get-Size([int]$g) {
    switch ($g) {
        0 { @{ W = 1; H = 4 } }; 1 { @{ W = 1; H = 3 } }; 2 { @{ W = 1; H = 3 } }
        3 { @{ W = 1; H = 4 } }; 4 { @{ W = 2; H = 3 } }; 5 { @{ W = 1; H = 4 } }
        6 { @{ W = 2; H = 2 } }; 7 { @{ W = 2; H = 2 } }; 8 { @{ W = 2; H = 3 } }
        9 { @{ W = 2; H = 2 } }; 10 { @{ W = 2; H = 2 } }; 11 { @{ W = 2; H = 2 } }
        12 { @{ W = 2; H = 3 } }; 13 { @{ W = 1; H = 1 } }; 14 { @{ W = 1; H = 1 } }
        default { @{ W = 1; H = 1 } }
    }
}

$modelMap = @{}
foreach ($m in $models) { $modelMap["$($m.Group):$($m.Number)"] = $m }

# Known Mudream pets that the auto-mapper left empty but BMDs exist under Skin/.
$manualModels = @{
    '13:336' = @{ Dir = 'Data\Item\CustomItem\Skin\Juggernaut\'; File = 'Juggernaut' }
    '13:398' = @{ Dir = 'Data\Item\CustomItem\Skin\Blackray\'; File = 'Blackray_horse' }
    '13:399' = @{ Dir = 'Data\Item\CustomItem\Skin\Blackray\'; File = 'Blackray_fenrir' }
    # Auto-mapper picked the first BMD in the folder, which put the bow mesh on the pet.
    '13:401' = @{ Dir = 'Data\Item\CustomItem\Skin\Elegance\'; File = 'Elegance_uniria' }
    # These four sets ship no per-class helm, only the _helm_Inventory_m/_f mesh, so the
    # auto-mapper fell through to a weapon and the helm rendered as a bow (or a box).
    '7:344' = @{ Dir = 'Data\Item\CustomItem\Skin\Blackpumpkin\'; File = 'Blackpumpkin_helm_Inventory_m' }
    '7:345' = @{ Dir = 'Data\Item\CustomItem\Skin\Blackpumpkin\'; File = 'Blackpumpkin_helm_Inventory_f' }
    '7:348' = @{ Dir = 'Data\Item\CustomItem\Skin\Evilrabbit\'; File = 'Evilrabbit_helm_Inventory_m' }
    '7:349' = @{ Dir = 'Data\Item\CustomItem\Skin\Evilrabbit\'; File = 'Evilrabbit_helm_Inventory_f' }
    '7:350' = @{ Dir = 'Data\Item\CustomItem\Skin\Hellfire\'; File = 'Hellfire_helm_Inventory_m' }
    '7:351' = @{ Dir = 'Data\Item\CustomItem\Skin\Hellfire\'; File = 'Hellfire_helm_Inventory_f' }
    '7:352' = @{ Dir = 'Data\Item\CustomItem\Skin\Macabre\'; File = 'Macabre_helm_Inventory_m' }
    '7:353' = @{ Dir = 'Data\Item\CustomItem\Skin\Macabre\'; File = 'Macabre_helm_Inventory_f' }
}
foreach ($k in $manualModels.Keys) {
    $modelMap[$k] = [pscustomobject]$manualModels[$k]
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated by OpenMU/tools/gen_mudream_cosmetic_client.ps1>')
[void]$sb.AppendLine('#include "stdafx.h"')
[void]$sb.AppendLine('#include "MudreamCosmeticLoader.h"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace MudreamCosmetics')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('const CosmeticItemEntry kItems[] = {')
foreach ($it in ($catalog | Sort-Object Group, Number)) {
    $key = "$($it.Group):$($it.Number)"
    $sz = Get-Size ([int]$it.Group)
    $slot = Get-Slot ([int]$it.Group) ([string]$it.Name)
    $name = ($it.Name -replace '\\', '\\' -replace '"', '\"')
    $dir = ''; $file = ''
    if ($modelMap.ContainsKey($key)) {
        # The model map mixes single- and already-doubled separators; collapse first so
        # every path ends up escaped exactly once for the C++ string literal.
        $dir = ($modelMap[$key].Dir -replace '\\\\', '\' -replace '\\', '\\')
        $file = $modelMap[$key].File
    }
    [void]$sb.AppendLine("    { $($it.Group), $($it.Number), L`"$name`", $($sz.W), $($sz.H), $slot, L`"$dir`", L`"$file`" },")
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('const int kItemCount = sizeof(kItems) / sizeof(kItems[0]);')
[void]$sb.AppendLine('} // namespace MudreamCosmetics')

$out = Join-Path $root 'MuMain\src\source\Data\GameData\ItemData\MudreamCosmeticCatalog.Generated.cpp'
$sb.ToString() | Set-Content $out -Encoding UTF8
Write-Host "Generated $($catalog.Count) client cosmetic entries -> $out"
