# Parses Mudream Tooltip.xml and regenerates MudreamCosmeticItemCatalog.Generated.cs
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$tooltip = Join-Path $root 'Mudream.online\Data\Local\ItemTooltip\Tooltip.xml'
[xml]$xml = Get-Content $tooltip -Encoding UTF8
$items = @()
foreach ($it in $xml.ItemTooltip.Item) {
    $idx = [int]$it.Index
    $typ = [int]$it.Type
    $cosmetic = $false
    foreach ($t in $it.Text) { if ($t.TextIndex -eq '966') { $cosmetic = $true; break } }
    if ($cosmetic -or $idx -ge 300) {
        $items += [pscustomobject]@{ Group = $typ; Number = $idx; Name = $it.Name; Cosmetic = $cosmetic }
    }
}

function Get-Slot([int]$g, [string]$name) {
    # Equipment slot index (NOT item group). Matches MuMain EQUIPMENT_* constants.
    switch ($g) {
        { $_ -in 0,1,2,3,5 } { return 0 }  # weapons → right hand
        # Group 4 splits by hand: bows sit in the shield slot like the vanilla ones,
        # crossbows are held in the weapon hand the way a sword is.
        4 { if ($name -match 'crossbow') { return 0 } else { return 1 } }
        6 { return 1 }   # shield → left hand
        7 { return 2 }   # helm
        8 { return 3 }   # armor
        9 { return 4 }   # pants
        10 { return 5 }  # gloves
        11 { return 6 }  # boots
        12 { return 7 }  # wings / cloak
        13 { return 8 }  # helper / pet / fenrir
        default { return 255 } # inventory-only (cores, dyes, etc.)
    }
}
function Get-Size([int]$g) {
    switch ($g) {
        0 { return @{W=1;H=4} }   # sword / blade / dagger / claw
        1 { return @{W=1;H=3} }   # axe
        2 { return @{W=1;H=3} }   # scepter / mace
        3 { return @{W=1;H=4} }   # spear
        4 { return @{W=2;H=3} }   # bow / crossbow
        5 { return @{W=1;H=4} }   # staff / stick
        6 { return @{W=2;H=2} }   # shield
        7 { return @{W=2;H=2} }   # helm
        8 { return @{W=2;H=3} }   # armor
        9 { return @{W=2;H=2} }   # pants
        10 { return @{W=2;H=2} }  # gloves
        11 { return @{W=2;H=2} }  # boots
        12 { return @{W=2;H=3} }  # wings / cloak
        13 { return @{W=1;H=1} }  # pet
        14 { return @{W=1;H=1} }  # utility
        default { return @{W=1;H=1} }
    }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated by OpenMU/tools/import_mudream_cosmetics_catalog.ps1>')
[void]$sb.AppendLine('namespace MUnique.OpenMU.Persistence.Initialization.Updates;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('internal static class MudreamCosmeticItemCatalog')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    internal static readonly MudreamCosmeticItem[] Items =')
[void]$sb.AppendLine('    [')
foreach ($item in ($items | Sort-Object Group, Number)) {
    $sz = Get-Size $item.Group
    $slot = Get-Slot $item.Group ([string]$item.Name)
    $name = ($item.Name -replace '"','\"')
    [void]$sb.AppendLine("        new($($item.Group), $($item.Number), `"$name`", $($sz.W), $($sz.H), $slot),")
}
[void]$sb.AppendLine('    ];')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    internal sealed record MudreamCosmeticItem(byte Group, short Number, string Name, byte Width, byte Height, byte Slot);')
[void]$sb.AppendLine('}')

$csPath = Join-Path $root 'OpenMU\src\Persistence\Initialization\Updates\MudreamCosmeticItemCatalog.Generated.cs'
$sb.ToString() | Set-Content $csPath -Encoding UTF8
$outJson = Join-Path $root 'OpenMU\tools\mudream_cosmetic_catalog.json'
$items | ConvertTo-Json -Depth 3 | Set-Content $outJson -Encoding UTF8
Write-Host "Catalog: $($items.Count) items -> $csPath"
