<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Donate') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to('/donate') ?>" data-ajax><?= __('Donate') ?></a></li>
            <li class="breadcrumb-item active"><?= $gateway ?></li>
        </ol>
    </nav>

    <h2 class="title"><?= __('Donate via %s', [$gateway]) ?></h2>
    <form data-ajax action="<?= url_to('/donate/' . $gateway) ?>" class="form" method="post">
        <?= function_exists('csrf_field') ? csrf_field() : '' ?>

        <div class="form-group">
            <label class="form-control-label" for="amount"><?= __('Value') ?> <span class="required">*</span></label>
            <input class="form-control" type="text" id="amount" name="amount" />
        </div>

        <?php if (isset($config['require_cpf']) && $config['require_cpf']): ?>
            <div class="form-group">
                <label class="form-control-label" for="amount"><?= __('CPF') ?> <span class="required">*</span></label>
                <input class="form-control" type="text" id="cpf" name="cpf" />
            </div>
        <?php endif ?>

        <?php if (isset($config['require_phone']) && $config['require_phone']): ?>
            <div class="form-group">
                <label class="form-control-label" for="phone"><?= __('Phone') ?> <span class="required">*</span></label>
                <input class="form-control" type="text" id="phone" name="phone" />
            </div>
        <?php endif ?>

        <?php if (isset($config['currency']) && $config['currency']): ?>
            <div class="form-group">
                <label class="form-control-label" for="currency"><?= __('Currency') ?> <span class="required">*</span></label>
                <select class="form-control" id="currency" name="currency">
                    <?php foreach ($currencies as $code => $currency): ?>
                        <option value="<?= $code ?>"><?= $currency ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        <?php endif ?>

        <input type="submit" class="btn btn-info" value="<?= __('Continue') ?>">

    </form>
</div>