<section class="content-header">
    <h1>
        <?= __('Market') ?>
        <small><?= __('Plugins') ?></small>
    </h1>
</section>

<section class="content">
    <div class="row row docs-premium-template">
        <?php foreach ($plugins as $plugin): ?>
            <div class="col-xs-6">
                <div class="box box-solid" style="margin-bottom:20px;">
                    <div class="box-body">
                        <h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">
                            <?= $plugin['name'] ?>
                        </h4>

                        <div class="media">
                            <div class="media-left">
                                <img src="<?= MORPHEUS_WEBSITE ?>files/Plugins/image/<?= $plugin['image'] ?>" alt="<?= $plugin['name'] ?>" class="media-object" style="width:auto;height:100px;border-radius: 4px;box-shadow: 0 1px 3px rgba(0,0,0,.15);">
                            </div>
                            <div class="media-body">
                                <div class="clearfix">
                                    <h4 style="margin-top: 0"><?= __('Price') ?> ─ <?= util('Number')->currency($plugin['price']) ?></h4>

                                    <p><?= util('Text')->truncate($plugin['description'], 50, ' ') ?></p>
                                    <p>
                                        <i class="fa fa-user margin-r5"></i> <?= $plugin['author'] ?>
                                    </p>

                                    <a href="<?= $plugin['website'] ?>" target="_blank" class="btn btn-success btn-sm"><?= __('Buy') ?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        <?php endforeach ?>
    </div>
</section>