<section class="content-header">
    <h1><?= __('Edit character') ?></h1>
</section>

<section class="content">
    <div class="box box-default">
        <form data-ajax class="form-horizontal form-focus" method="post" action="<?= url_to('/admin/characters/edit/' . $character['name']) ?>">
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-name"><?= __('Name') ?> <span class="required">*</span></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['name'] ?>" name="name" id="character-name" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-level"><?= __('Level') ?> <span class="required">*</span></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['level'] ?>" name="level" id="character-level" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-class"><?= __('Class') ?></label>

                            <div class="col-sm-9">
                                <select class="form-control" name="class" id="character-class">
                                    <?php foreach (config('characters.classes', []) as $code => $class): ?>
                                        <option value="<?= $code ?>"<?= $character['class'] == $code ? ' selected="selected"' : '' ?>><?= $class['name'] ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-map"><?= __('Map') ?></label>

                            <div class="col-sm-9">
                                <select class="form-control" name="map" id="character-map">
                                    <?php foreach (config('maps', []) as $code => $map): ?>
                                        <option value="<?= $code ?>"<?= $character['map'] == $code ? ' selected="selected"' : '' ?>><?= $map['name'] ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-strength"><?= __('Strength') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['strength'] ?>" name="strength" id="character-strength" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-energy"><?= __('Energy') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['energy'] ?>" name="energy" id="character-energy" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-command"><?= __('Command') ?></label>

                            <div class="col-sm-9">
                                <?php if (isset($character['command'])): ?>
                                    <input class="form-control" type="text" value="<?= $character['command'] ?>" name="command" id="character-command" />
                                <?php else: ?>
                                    <p class="form-control-static">-</p>
                                <?php endif ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-money"><?= __('Zen') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['money'] ?>" name="money" id="character-money" />
                            </div>
                        </div>

                        <?php if (config('columns.resets')): ?>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="character-resets"><?= __('Resets') ?></label>

                                <div class="col-sm-9">
                                    <input class="form-control" type="text" value="<?= $character['resets'] ?>" name="resets" id="character-resets" />
                                </div>
                            </div>
                        <?php endif ?>
                    </div>

                    <div class="col-xs-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?= __('Account') ?></label>

                            <div class="col-sm-9">
                                <p class="form-control-static"><a data-ajax href="<?= url_to('/admin/accounts/edit/' . $character['username']) ?>"><?= $character['username'] ?></a></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-experience"><?= __('Experience') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['experience'] ?>" name="experience" id="character-experience" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-points"><?= __('Points') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['points'] ?>" name="points" id="character-points" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-x"><?= __('Coordinates') ?> <span class="required">*</span></label>

                            <div class="col-sm-9">
                                <div class="input-group" style="width:100%">
                                    <input class="form-control" type="text" style="width:48%" value="<?= $character['positionX'] ?>" name="x" id="character-x" />
                                    <input class="form-control" type="text" style="width:49%;float:right" value="<?= $character['positionY'] ?>" name="y" id="character-y" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-agility"><?= __('Agility') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['agility'] ?>" name="agility" id="character-agility" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-vitality"><?= __('Vitality') ?></label>

                            <div class="col-sm-9">
                                <input class="form-control" type="text" value="<?= $character['vitality'] ?>" name="vitality" id="character-vitality" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-code"><?= __('Type') ?></label>

                            <div class="col-sm-9">
                                <select class="form-control" name="code" id="character-code">
                                    <?php foreach (config('characters.code_types', []) as $code => $name): ?>
                                        <option value="<?= $code ?>"<?= $character['code'] == $code ? ' selected="selected"' : '' ?>><?= $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>

                        <?php if (isset($character['ruud'])): ?>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="character-ruud"><?= __('Ruud') ?></label>

                                <div class="col-sm-9">
                                    <input class="form-control" type="text" value="<?= $character['ruud'] ?>" name="ruud" id="character-ruud" />
                                </div>
                            </div>
                        <?php endif ?>

                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="character-pk"><?= __('PK Level') ?></label>

                            <div class="col-sm-9">
                                <select class="form-control" name="pk" id="character-pk">
                                    <?php foreach (config('characters.pk_levels', []) as $code => $name): ?>
                                        <option value="<?= $code ?>"<?= $character['pkLevel'] == $code ? ' selected="selected"' : '' ?>><?= $name ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>

                        <?php if (config('columns.master_resets')): ?>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="character-master-resets"><?= __('Master Resets') ?></label>

                                <div class="col-sm-9">
                                    <input class="form-control" type="text" value="<?= $character['masterResets'] ?>" name="master_resets" id="character-master-resets" />
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                </div>

                <?php notify('admin.characters.edit.render', $character) ?>
            </div>

            <div class="box-footer">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="col-sm-offset-3" style="padding-left:8px">
                            <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
