<section class="content-header">
    <h1><?= __('Players online') ?></h1>
</section>

<div class="modal" id="modal-map" data-width="512"></div>

<section class="content">
    <?php if (empty($servers)): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No characters currently online') ?></p>
        </div>
    <?php else: ?>
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <?php $i = 0; foreach ($servers as $server => $character): ?>
                    <li class="<?= $i == 0 ? 'active' : '' ?>"><a data-toggle="tab" href="#tab-<?= util('Inflector')->slug($server) ?>"><?= $server ?></a></li>
                <?php $i++; endforeach ?>
            </ul>

            <div class="tab-content" style="padding:0">
                <?php $i = 0; foreach ($servers as $server => $characters): ?>
                    <div class="tab-pane<?= $i == 0 ? ' active' : '' ?>" id="tab-<?= util('Inflector')->slug($server) ?>">
                        <table class="table table-condensed table-hover table-striped">
                            <thead>
                                <tr>
                                    <th><?= __('Character') ?></th>
                                    <th><?= __('Account') ?></th>
                                    <th><?= __('Time online') ?></th>
                                    <th>IP</th>
                                    <th><?= __('Server') ?></th>
                                    <th width="10"></th>
                                </tr>
                            </thead>

                            <tbody>
                                <?php if (empty($characters)): ?>
                                    <tr>
                                        <td colspan="6"><?= __('No characters currently online') ?></td>
                                    </tr>
                                <?php else: ?>
                                    <?php foreach ($characters as $character): ?>
                                        <tr>
                                            <td><a data-ajax href="<?= url_to('/admin/characters/edit/' . $character['character']) ?>"><?= $character['character'] ?></a></td>
                                            <td><a data-ajax href="<?= url_to('/admin/accounts/edit/' . $character['account']) ?>"><?= $character['account'] ?></a></td>
                                            <td><?= util('Time')->relative($character['connected_at']) ?></td>
                                            <td><?= $character['ip'] ?></td>
                                            <td><?= $character['server_name'] ?></td>
                                            <td class="record-actions">
                                                <a data-load-with-modal data-modal="modal-map" class="btn btn-xs btn-default" href="<?= url_to('/admin/characters/map/' . $character['character']) ?>"><?= __('In map') ?></a>
                                                <a class="btn btn-xs btn-default" data-ajax-action data-confirm="<?= __('You are sure?') ?>" href="<?= url_to('/admin/accounts/logout/' . $character['account']) ?>"><?= __('Disconnect') ?></a>
                                            </td>
                                        </tr>
                                    <?php endforeach ?>
                                <?php endif ?>
                            </tbody>
                        </table>
                    </div>
                <?php $i++; endforeach ?>
            </div>
        </div>
    <?php endif ?>
</section>