<section class="content-header">
    <h1><?= __('Edit slide') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/slides') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">
    <div class="box box-default">
        <form data-ajax data-upload class="form-horizontal form-action" action="<?= url_to('/admin/slides/edit/' . $slide['id']) ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="slides-image"><?= __('Image') ?> <span class="required">*</span></label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input data-upload-field class="form-control" type="file" name="image" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="slides-title"><?= __('Title') ?></label>

                    <div class="col-sm-6">
                        <input class="form-control" value="<?= $slide['title'] ?>" type="text" name="title" id="slides-title" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="slides-url"><?= __('URL') ?></label>

                    <div class="col-sm-6">
                        <input class="form-control"  value="<?= $slide['url'] ?>" type="text" name="url" id="slides-url" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="slides-active"><?= __('Active') ?>?</label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input class="form-control" type="checkbox"<?= $slide['active'] ? ' checked' : '' ?> id="slides-active" value="1" name="active" />
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>