<section class="content-header">
    <h1><?= __('Slides') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-success btn-sm" href="<?= url_to('/admin/slides/add') ?>"><?= __('Add') ?></a>
    </div>
</section>

<section class="content">
    <?php if (empty($slides)): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No slides found') ?></p>
        </div>
    <?php else: ?>
        <div class="box box-default table-responsive">
            <table id="shops-table" class="table table-condensed table-hover table-striped">
                <thead>
                <tr>
                    <th width="10"></th>
                    <th><?= __('Title') ?></th>
                    <th><?= __('URL') ?></th>
                    <th width="80"></th>
                </tr>
                </thead>

                <tbody>
                <?php foreach ($slides as $slide): ?>
                    <tr class="<?= !$slide['active'] ? 'danger' : '' ?>">
                        <td><img height="50" src="<?= upload_to('/slides/' . $slide['image']) ?>" /></td>
                        <td><?= $slide['title'] ?></td>
                        <td><?= $slide['url'] ?></td>
                        <td class="record-actions">
                            <a data-ajax class="btn btn-xs btn-default" href="<?= url_to('/admin/slides/edit/' . $slide['id']) ?>"><?= __('Edit') ?></a>
                            <a data-ajax-delete class="btn btn-danger btn-xs" href="<?= url_to('/admin/slides/delete/' . $slide['id']) ?>"><?= __('Delete') ?></a>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</section>
