<section class="content-header">
    <h1><?= __('Edit new news') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/news') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">

    <div class="box box-default">
        <form data-upload data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/news/edit/' . $news->getId()) ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="news-title"><?= __('Title') ?> <span class="required">*</span></label>

                    <div class="col-sm-8">
                        <input class="form-control" type="text" value="<?= $news->getTitle() ?>" name="title" id="news-title" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="news-link">URL</label>

                    <div class="col-sm-8">
                        <input class="form-control" type="text" value="<?= $news->getLink() ?>" name="link" id="news-link" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="product-image"><?= __('Image cover') ?></label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input data-upload-field class="form-control" type="file" name="image_cover" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="news-type"><?= __('Category') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <select class="form-control" name="type" id="news-type">
                            <option value=""></option>
                            <?php foreach (config('news.types', []) as $id => $type): ?>
                                <option<?= $news->getType() == $id ? ' selected' : '' ?> value="<?= $id ?>"><?= $type['name'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="config-allow-comments"><?= __('Allow comments') ?>?</label>

                    <div class="col-sm-10" style="padding-top:5px;padding-bottom:5px">
                        <input<?= config('news.allow_comments') ? '' : ' disabled' ?> class="form-control" type="checkbox" id="config-allow-comments"<?= $news->isAllowedComments() ? 'checked="checked"' : '' ?> value="1" name="allow_comments" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="news-body"><?= __('News') ?> <span class="required">*</span></label>

                    <div class="col-sm-10">
                        <textarea class="form-control editor" name="body" id="news-body"><?= $news->getBody() ?></textarea>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>