<?= partial('rates') ?>

<p style="margin-bottom:2px;"><span class="required">*</span> <?= __('Quantity of resets available: %d', [$character->getResets()]) ?></p>

<form style="margin-top:10px" data-ajax action="<?= url_to('/panel/character/' . $character->getName() . '/transfer-resets') ?>" class="form" method="post">
    <?= function_exists('csrf_field') ? csrf_field() : '' ?>

    <div class="form-group">
        <label class="form-control-label" for="resets"><?= __('Quantity of resets') ?> <span class="required">*</span></label>
        <input class="form-control" type="text" id="resets" name="resets" />
    </div>

    <div class="form-group">
        <label class="form-control-label" for="character"><?= __('Target character') ?> <span class="required">*</span></label>
        <select class="form-control" id="character" name="character">
            <option value=""></option>
            <?php foreach ($available as $name): ?>
                <option value="<?= $name ?>"><?= $name ?></option>
            <?php endforeach ?>
        </select>
    </div>

    <input type="submit" class="btn btn-info" value="<?= __('Transfer') ?>">
</form>