<script type="text/javascript">
    function byType() {
        var val = $("#config-use-type").val();
        console.log(val);
        if (val == "1") {
            $(".by-category").show();
            $(".by-upload").hide();
        } else if (val == "2") {
            $(".by-category").hide();
            $(".by-upload").show();
        } else {
            $(".by-category").hide();
            $(".by-upload").hide();
        }
    }

    $(function () {
        byType();

        $("#config-use-type").change(function () {
            console.log('a');
            byType();
        });

        $(document).on("click", ".add-department", function (e) {
            var $this = $(this);
            var $container = $this.closest("form").find(".container-add-category");
            var index = $container.find(":input").size() + 1;
            $container.append('<input class="form-control" type="text" style="margin-top:3px;" name="categories[]" />');
            e.preventDefault();
        });
    });
</script>

<section class="content-header">
    <h1><?= __('Settings plugin avatar') ?></h1>
</section>

<section class="content">

    <div class="box box-default">
        <form data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/configs/avatar') ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="config-use-type"><?= __('Use type') ?></label>

                    <div class="col-sm-3">
                        <select class="form-control" name="use_type" id="config-use-type">
<!--                            <option value="1"--><?//= config('avatar.use_type') == 1 ? ' selected' : '' ?><!-->--><?//= __('by category') ?><!--</option>-->
                            <option value="2"<?= config('avatar.use_type') == 2 ? ' selected' : '' ?>><?= __('Upload') ?></option>
                        </select>
                    </div>
                </div>

                <div class="by-category" style="display:none">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="config-avatar"><?= __('Categories') ?></label>

                        <div class="col-sm-10 container-add-category">
                            <?php foreach (config('avatar.categories', []) as $category): ?>
                                <input class="form-control" type="text" style="margin-bottom:3px;" value="<?= $category ?>" name="categories[]" />
                            <?php endforeach ?>
                            <input class="form-control" type="text" name="categories[]" />
                        </div>
                    </div>

                    <div style="text-align:right;margin-top:-10px;margin-bottom:10px;">
                        <a class="btn btn-success btn-xs add-department" href="javascript:void(0)"><?= __('Add') ?></a>
                    </div>
                </div>

                <div class="by-upload" style="display:none">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="config-filesize"><?= __('Filesize') ?></label>

                        <div class="col-sm-2">
                            <input class="form-control" value="<?= config('avatar.filesize', 100) ?>" type="text" id="config-filesize" name="filesize" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="config-gif"><?= __('GIF image') ?>?</label>

                        <div class="col-sm-10" style="padding-top:5px">
                            <input class="form-control" type="checkbox"<?= config('avatar.allow_gif', false) ? ' checked' : '' ?> id="config-gif"<?= config('avatar.gif', false) ? 'checked="checked"' : '' ?> value="1" name="allow_gif" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>