<div class="events-container">
    <div class="events-header">
        <p class="title"><?= __('Events') ?></p>
        <p class="description">
            <?= __('Not be late, the next event will start soon.') ?>
        </p>
    </div>

    <div class="events-content">
        <div class="events-spotlight"></div>
    </div>
</div>

<a class="more-link" data-ajax href="<?= url_to('/events') ?>" class="btn">
    <i class="fa fa-plus"></i> <?= __('All events') ?>
</a>
