<section class="content-header">
    <h1><?= __('Coupons') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-success btn-sm" href="<?= url_to('/admin/webshop/coupons/add') ?>"><?= __('Add') ?></a>
    </div>
</section>

<section class="content">
    <?php if (empty($coupons)): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No coupons found') ?></p>
        </div>
    <?php else: ?>
        <div class="box box-default table-responsive">
            <table id="shops-table" class="table table-condensed table-hover table-striped">
                <thead>
                    <tr>
                        <th><?= __('Coupon') ?></th>
                        <th><?= __('Start date') ?></th>
                        <th><?= __('Expire date') ?></th>
                        <th><?= __('Discount') ?></th>
                        <th width="80"></th>
                    </tr>
                </thead>

                <tbody>
                    <?php foreach ($coupons as $coupon): ?>
                        <tr class="<?= !$coupon['active'] ? 'danger' : '' ?>">
                            <td><?= $coupon['coupon'] ?></td>
                            <td><?= util('Date')->date($coupon['start_date']) ?></td>
                            <td><?= util('Date')->date($coupon['expire_date']) ?></td>
                            <td><?= $coupon['discount'] ?>%</td>
                            <td class="record-actions">
                                <a data-ajax class="btn btn-xs btn-default" href="<?= url_to('/admin/webshop/coupons/edit/' . $coupon['id']) ?>"><?= __('Edit') ?></a>
                                <a data-ajax-delete class="btn btn-danger btn-xs" href="<?= url_to('/admin/webshop/coupons/delete/' . $coupon['id']) ?>"><?= __('Delete') ?></a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</section>
