<?php

return [
    'Market' => 'Mercado',
    'Items for sale' => 'Ítens para venda',
    'Buy' => 'Comprar',
    'Sell item' => 'Vender item',
    'Sell' => 'Vender',
    'Price' => 'Preço',
    'Bought date' => 'Comprado em',
    'remove' => 'Remover',
    'My items' => 'Meus ítens',
    'Extended' => 'Extendido',
    'Payment type' => 'Tipo de pagamento',
    'Coin' => 'Moeda',

    'The item was successfully purchased' => 'Item comprado com sucesso',
    'Item added to the market' => 'Item adicionado ao mercado com sucesso',
    'Item has been added in your warehouse' => 'Item removido do mercado e adicionado ao seu baú com sucesso',
    'No space in your warehouse' => 'Não existe espaço no seu baú',
    'Item doen\'t exists' => 'Item não encontrado',
    'No space in the seller\'s warehouse' => 'O vendedor não possui espaço em seu baú para concluir a compra',
    'You don\'t have enough %s' => 'Você não possui %s suficientes',
    'This item is already on the market' => 'Este item já está no mercado',
    'Payment is not allowed' => 'Tipo de pagamento não liberado'
];