<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= $title ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to($root['url']) ?>" data-ajax><?= $root['name'] ?></a></li>
            <li class="breadcrumb-item active"><?= $currentService['name'] ?></li>
        </ol>
    </nav>

    <div class="panel">
        <div class="row">
            <div class="col-md-4">
                <div class="list-group">
                    <?php foreach ($services as $serv): ?>
                        <a class="list-group-item list-group-item-action<?= $serv['current'] ? ' active' : '' ?>" data-ajax href="<?= url_to($serv['url']) ?>"><?= $serv['name'] ?></a>
                    <?php endforeach ?>
                </div>
            </div>

            <div class="col-md-8">
                <?= $service ?>
            </div>
        </div>
    </div>
</div>