<section class="sidebar">
    <form data-account-find autocomplete="off" action="<?= url_to('/admin/accounts/find') ?>" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="term" autocomplete="off" class="form-control" placeholder="<?= __('Search') ?>...">
            <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </form>

    <?= Morpheus\Menu\Menu::getInstance('admin')->render() ?>
</section>