<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Auctions') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item active"><?= __('Auctions') ?></li>
        </ol>
    </nav>

    <?php if (!empty($auctions)): ?>
        <table class="table table-sm">
            <thead class="thead-dark">
                <tr>
                    <th><?= __('Name') ?></th>
                    <th width="10"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($auctions as $auction): ?>
                    <tr>
                        <td><?= $auction['name'] ?></td>
                        <td>
                            <a data-ajax class="btn btn-info btn-sm" href="<?= url_to('/auctions/items/' . $auction['id']) ?>"><?= __('Enter') ?></a>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="alert alert-warning"><?= __('No auction currently open') ?></div>
    <?php endif ?>

</div>
