<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Auction') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to('/auctions') ?>" data-ajax><?= __('Auctions') ?></a></li>
            <li class="breadcrumb-item active"><?= $auction['name'] ?></li>
        </ol>
    </nav>

    <div class="auction-items">
        <div class="form-row items">
            <?php foreach ($items as $item): ?>
                <div class="col-lg-4 col-sm-6">
                    <div class="card item" style="margin-bottom:10px" data-id="<?= $item['id'] ?>" data-time-end="<?= config('auction.close_time', 60) ?>" data-now="<?= strtotime('now') ?>" data-time="<?= strtotime($item['best_bid_date']) ?>">
                        <div class="card-header" style="text-align:center">
                            <?= util('Item')->getFullName($item['item']) ?>
                        </div>

                        <div class="card-body" style="text-align:center">
                            <div class="image" data-tooltip data-tooltip-url="<?= resource_to('/item.php?hex=' . $item['item']->getHex()) ?>">
                                <img src="<?= util('Item')->getImage($item['item']) ?>" />
                            </div>

                            <div class="info">
                                <?= __('Initial bid') ?>: <?= $item['initial_bid'] ?> <?= util('Coin')->name($item['coin']) ?><br />
                                <?= __('Best bid') ?>:
                                <div>
                                    <?= $item['best_bid'] ?> <?= util('Coin')->name($item['coin']) ?>
                                    <?php if (!empty($item['best_bid_name'])): ?>
                                        <?= __('by') ?> <?= $item['best_bid_name'] ?>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer d-flex justify-content-between">
                            <div class="time align-center" style="margin-top:10px">00:00</div>

                            <div class="buy">
                                <a data-id="<?= $item['id'] ?>" href="<?= url_to('/auction/bid/' . $item['id']) ?>" class="btn btn-info auction-bid"><?= __('Bid') ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>