<?php View::add('page.title', __('Change password')) ?>

<p style="margin-bottom:2px;"><span class="required">*</span> <?= __('It\'s important that you don\'t forget your new password') ?></p>
<p style="margin-bottom:10px;"><span class="required">*</span> <?= __('We suggest that you change your password periodically for your safety') ?></p>

<form data-ajax action="<?= url_to('/panel/account/change-password') ?>" class="form" method="post">
    <?= function_exists('csrf_field') ? csrf_field() : '' ?>

    <div class="form-group">
        <label class="form-control-label" for="current-password"><?= __('Current password') ?> <span class="required">*</span></label>
        <input class="form-control" type="password" id="current-password" name="current_password" maxlength="10" />
    </div>
    <div class="form-group">
        <label class="form-control-label" for="password"><?= __('New password') ?> <span class="required">*</span></label>
        <input class="form-control" type="password" id="password" name="password" maxlength="10" />
    </div>
    <div class="form-group">
        <label class="form-control-label" for="repassword"><?= __('Repeat password') ?> <span class="required">*</span></label>
        <input class="form-control" type="password" id="repassword" name="repassword" maxlength="10" />
    </div>

    <input type="submit" class="btn btn-info" value="<?= __('Change') ?>">
</form>