<?php View::add('page.title', __('Change PID')) ?>


<p style="margin-bottom:2px;"><span class="required">*</span> <?= __('It\'s important that you don\'t forget your new key') ?></p>
<p style="margin-bottom:10px;"><span class="required">*</span> <?= __('We suggest that you change your key periodically for your safety') ?></p>

<form data-ajax action="<?= url_to('/panel/account/change-pid') ?>" class="form" method="post">
    <?= function_exists('csrf_field') ? csrf_field() : '' ?>

    <div class="form-group">
        <label class="form-control-label" for="current-pid"><?= __('Current pid') ?> <span class="required">*</span></label>
        <input class="form-control" type="text" id="current-pid" name="current_pid" maxlength="7" />
    </div>
    <div class="form-group">
        <label class="form-control-label" for="pid"><?= __('New pid') ?> <span class="required">*</span></label>
        <input class="form-control" type="text" id="pid" name="pid" maxlength="7" style="width:100%" />
    </div>
    <div class="form-group">
        <label class="form-control-label" for="repid"><?= __('Repeat pid') ?> <span class="required">*</span></label>
        <input class="form-control" type="text" id="repid" name="repid" maxlength="7" style="width:100%" />
    </div>

    <input type="submit" class="btn btn-info" value="<?= __('Change') ?>">
</form>