<?php View::add('page.title', __('Forgot password')) ?>

<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Recover password') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item active"><?= __('Recover password') ?></li>
        </ol>
    </nav>

    <form data-ajax action="<?= url_to('/forgot-password') ?>" class="form" method="post">
        <?= function_exists('csrf_field') ? csrf_field() : '' ?>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="form-control-label" for="username"><?= __('Username') ?> <span class="required">*</span></label>
                    <input class="form-control" type="text" id="username" name="username" maxlength="10" />
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="form-control-label" for="email"><?= __('E-mail') ?> <span class="required">*</span></label>
                    <input class="form-control" type="text" id="email" name="email" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="captcha">
                <div class="img">
                    <img src="<?= url_to('/captcha?t=' . time()) ?>" height="70" width="200" />
                    <a href="#" tabindex="-1" class="reload-captcha">
                        <i class="fa fa-sync"></i>
                    </a>
                </div>
                <div class="clear"></div>
                <input class="form-control" type="text" name="captcha" id="captcha" />
            </div>
        </div>

        <input type="submit" class="btn btn-info" value="<?= __('Recover') ?>">
    </form>
</div>