<?php View::add('page.title', __('Generate password')) ?>

<div class="page-container">
    <h1 class="title"><?= __('Generate new password') ?></h1>

    <?php if ($error): ?>
        <div class="alert alert-danger"><?= $error ?></div>
    <?php else: ?>
        <div class="alert alert-success">
            <?= __('Your new password has been sent to your e-mail') ?>
        </div>
    <?php endif ?>
</div>
