<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Market') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
        <li class="breadcrumb-item active"><?= __('Market') ?></li>
    </ol>

    <?php if (!empty($myitems)): ?>
        <h2 class="title"><?= __('My items') ?></h2>
        <table class="table table-sm table-hover table-striped">
            <thead class="thead-dark">
                <tr>
                    <th><?= __('Name') ?></th>
                    <th><?= __('Price') ?></th>
                    <th><?= __('Bought date') ?></th>
                    <th width="10"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($myitems as $item): ?>
                    <tr>
                        <td><?= util('Item')->getFullName($item['item']) ?></td>
                        <td><?= $item['price'] ?> <?= util('Market.Market')->paymentName($item['payment_type'], $item['coin']) ?></td>
                        <td><?= util('Date')->date($item['bought_date']) ?></td>
                        <td>
                            <?php if (empty($item['bought_date'])): ?>
                                <a data-ajax-action href="<?= url_to('/market/remove/' . $item['id']) ?>"><?= __('remove') ?></a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    <?php endif ?>

    <div class="margin-top">
        <a data-ajax class="btn bg-orange" href="<?= url_to('/market/sell') ?>"><?= __('Sell item') ?></a>
    </div>

    <hr />

    <div class="row">
        <div class="col-sm-3">
            <form action="<?= url_to('/market') ?>" type="get">
                <input class="form-control" type="text" value="<?= isset($q) ? $q : '' ?>" name="q" placeholder="<?= __('Search') ?>" />
            </form>

            <h2 class="title" style="margin-top:10px"><?= __('Category') ?></h2>
            <div class="list-group">
                <?php foreach (config('item.categories') as $index => $category): ?>
                    <a class="list-group-item list-group-item-action" data-ajax href="<?= url_to('/market?category=' . $index) ?>"><?= $category ?></a>
                <?php endforeach ?>
            </div>
        </div>

        <div class="col-sm-9">
            <div class="shop">
                <div class="form-row items">
                    <?php foreach ($items as $item): ?>
                        <div class="col-sm-4">
                            <div class="card item">
                                <div class="card-header">
                                    <div class="name"><?= util('Item')->getFullName($item['item']) ?></div>
                                </div>
                                <div class="image" data-tooltip data-tooltip-url="<?= resource_to('/item.php?hex=' . $item['item']->getHex()) ?>">
                                    <img src="<?= util('Item')->getImage($item['item']) ?>" />
                                </div>
                                <div class="card-body text-center">
                                    <?= $item['price'] ?> <?= util('Market.Market')->paymentName($item['payment_type'], $item['coin']) ?>
                                </div>
                                <?php if (logged_in() && $item['account'] !== user()->getUsername()): ?>
                                    <div class="card-footer">
                                        <a data-ajax-action href="<?= url_to('/market/buy/' . $item['id']) ?>" class="btn btn-sm btn-info"><?= __('Buy') ?></a>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>

            <?= partial('paginator', compact('paginator')) ?>
        </div>
    </div>
</div>