<div class="page-container rank-u-bg">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Ranking') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>


    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item active"><?= __('Rankings') ?></li>
        </ol>
    </nav>

    <?= partial('rankings') ?>
</div>