<section class="content-header">
    <h1><?= __('Plugins') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-warning btn-sm" href="<?= url_to('/admin/market/plugins') ?>"><?= __('Market') ?></a>
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/plugins?check-updates') ?>"><?= __('Check updates') ?></a>
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/plugins/install') ?>"><?= __('Install') ?></a>
    </div>
</section>

<section class="content">

    <?php if (empty($plugins)): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No plugins found') ?></p>
        </div>
    <?php else: ?>

        <div class="box box-default table-responsive">
            <table data-table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th width="110"><?= __('Plugin') ?></th>
                        <th><?= __('Description') ?></th>
                        <th width="10"></th>
                    </tr>
                </thead>

                <?php foreach ($plugins as $plugin): ?>
                    <tr class="plugin-<?= $plugin['name'] ?> <?= $plugin['active'] ? ' border-success' : '' ?><?= $plugin['update'] !== false ? ' warning' : '' ?>">
                        <td><?= $plugin['name'] ?></td>
                        <td>
                            <?= $plugin['description'] ?>
                            <div style="margin-top:10px;color:#666">
                                <?= __('Version') ?> <span class="label label-warning"><?= $plugin['version'] ?></span>
                                <?php if ($plugin['update'] !== false): ?>
                                    <span class="label label-info new-version"><?= __('New version available %s', [$plugin['update']]) ?></span>
                                <?php endif ?>
                                | <?= __('by') ?> <a href="<?= $plugin['website'] ?>" target="_blank"><?= $plugin['author'] ?></a>
                            </div>
                        </td>
                        <td class="record-actions">
                            <?php if ($plugin['update'] !== false): ?>
                                <a data-ajax-action class="update btn btn-warning btn-xs" href="<?= url_to('/admin/plugins/update/' . $plugin['name']) ?>"><?= __('Update') ?></a>
                            <?php endif ?>
                            <?php if (isset($plugin['config_url']) && $plugin['active']): ?>
                                <a data-ajax class="btn btn-default btn-xs" href="<?= url_to('/admin' . $plugin['config_url']) ?>"><?= __('Config') ?></a>
                            <?php endif ?>
                            <?php if ($plugin['active']): ?>
                                <a data-ajax-action data-partial="sidebar" class="btn btn-danger btn-xs" href="<?= url_to('/admin/plugins/deactivate/' . $plugin['name']) ?>"><?= __('Deactivate') ?></a>
                            <?php else: ?>
                                <a data-ajax-action data-partial="sidebar" class="btn btn-success btn-xs" href="<?= url_to('/admin/plugins/active/' . $plugin['name']) ?>"><?= __('Activate') ?></a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    <?php endif ?>
</section>