<?php if ($blocked): ?>
    <div class="alert alert-warning text-center"><?= __('Item blocked for upgrade') ?></div>
<?php else: ?>
    <form class="form form-action" data-ajax action="<?= url_to($base . $slot . '/upgrade' . (isset($extended) && $extended !== null ? '?extended' : '')) ?>">
        <?= function_exists('csrf_field') ? csrf_field() : '' ?>

        <div id="workshop-item">
            <h2 class="title"><strong><?= $item->getName() ?></strong></h2>
            <div class="form-group">
                <label class="form-control-label" for="product-level"><?= __('Level') ?></label>
                <select class="form-control" data-default="<?= $item->getLevel() ?>" data-prices="<?= $prices['level'] ?>" name="level" id="item-level">
                    <?php $maxLevel = config('workshop.max_level', 0) ?>
                    <?php for ($i = 0; $i <= ($item->getLevel() > $maxLevel ? $item->getLevel() : $maxLevel); $i++): ?>
                        <option<?= $item->getLevel() === $i ? ' selected' : '' ?> value="<?= $i ?>">+<?= $i ?></option>
                    <?php endfor ?>
                </select>
            </div>

            <div class="form-group">
                <label class="form-control-label" for="product-option"><?= __('Option') ?></label>
                <select class="form-control" data-default="<?= $item->getOption() ?>" data-prices="<?= $prices['option'] ?>" name="option" id="item-option">
                    <?php $maxOption = config('workshop.max_option', 0) ?>
                    <?php for ($i = 0; $i <= ($item->getOption() > $maxOption ? $item->getOption() : $maxOption); $i+=4): ?>
                        <option<?= $item->getOption() == $i ? ' selected' : '' ?> value="<?= $i ?>">+<?= $i ?></option>
                    <?php endfor ?>
                </select>
            </div>

            <?php if (config('workshop.allow_ancient', 0) && $item->getAncient()->exists()): ?>
                <div class="form-group">
                    <label class="form-control-label" for="item-ancient"><?= __('Ancient') ?></label>
                    <select class="form-control" data-default="<?= $item->getAncient()->get() ?>" data-prices="<?= $prices['ancient'] ?>" name="ancient" id="item-ancient">
                        <option value="0"></option>
                        <?php foreach ($item->getAncient()->available() as $index => $name): ?>
                            <option<?= $item->getAncient()->is($index) ? ' selected' : '' ?> value="<?= $index ?>"><?= $name ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            <?php endif ?>

            <?php if ($item->getDefinitions()->hasSkill()): ?>
                <div class="form-group">
                    <input class="styled-checkbox"<?= $item->hasSkill() ? ' checked' : '' ?> data-default="<?= $item->hasSkill() ? 1 : 0 ?>" data-prices="<?= $prices['skill'] ?>" type="checkbox" id="item-skill" value="1" name="skill" />
                    <label for="item-skill"><?= __('Skill') ?></label>
                </div>
            <?php endif ?>

            <?php if ($item->getDefinitions()->hasLuck()): ?>
                <div class="form-group">
                    <input class="styled-checkbox"<?= $item->hasLuck() ? ' checked' : '' ?> data-default="<?= $item->hasLuck() ? 1 : 0 ?>" data-prices="<?= $prices['luck'] ?>" type="checkbox" id="item-luck" value="1" name="luck" />
                    <label for="item-luck"><?= __('Luck') ?></label>
                </div>
            <?php endif ?>

            <?php if ($item->getDefinitions()->hasExcellentOptions()): ?>
                <h2 class="title"><strong><?= __('Excelent options') ?></strong></h2>


                <?php foreach ($item->getDefinitions()->getExcellentOptions() as $index => $name): ?>
                    <div class="check">
                        <input class="styled-checkbox"<?= $item->getExcellent($index) ? ' checked' : '' ?> data-default="<?= $item->getExcellent($index) ? 1 : 0 ?>" data-prices="<?= $prices['excellent'] ?>" type="checkbox" id="item-excellent-<?= $index ?>" value="1" name="excellent[<?= $index ?>]" />
                        <label for="item-excellent-<?= $index ?>"><?= $name ?></label>
                    </div>
                <?php endforeach ?>
            <?php endif ?>

            <?php if (config('workshop.allow_refine', 0) && $item->getDefinitions()->hasRefine()): ?>
                <h2 class="title"><strong><?= __('Level 380 option') ?></strong></h2>

                <div class="form-group">
                    <input class="styled-checkbox"<?= $item->isRefine() ? ' checked' : '' ?> data-default="<?= $item->isRefine() ? 1 : 0 ?>" data-prices="<?= $prices['refine'] ?>" type="checkbox" id="item-refine" value="1" name="refine" />
                    <label for="item-refine"><?= __('Refine') ?></label>
                </div>

            <?php endif ?>

            <?php if (config('workshop.allow_harmony', 0) && $item->getDefinitions()->hasHarmony()): ?>
                <h2 class="title mt-3"><strong><?= __('Harmony options') ?></strong></h2>

                <div class="form-group">
                    <select class="form-control" data-default="<?= $item->getHarmony()->getType() > 0 ? ($item->getHarmony()->getType() . ',' . $item->getHarmony()->getLevel()) : '' ?>" data-prices="<?= $prices['harmony'] ?>" id="item-harmony" name="harmony" style="width:100%">
                        <option value=""></option>
                        <?php foreach ($item->getHarmony()->available() as $harmony):  ?>
                            <optgroup label="<?= substr($harmony['name'], 0, strlen($harmony['name']) - 3) ?>">
                                <?php foreach ($harmony['levels'] as $level): ?>
                                    <option<?= $item->getHarmony()->getType() === $harmony['index'] && $item->getHarmony()->getLevel() === $level['level'] ? ' selected' : '' ?> value="<?= $harmony['index'] ?>,<?= $level['level'] ?>"><?= sprintf($harmony['name'], $level['name']) ?></option>
                                <?php endforeach ?>
                            </optgroup>
                        <?php endforeach ?>
                    </select>
                </div>
            <?php endif ?>

            <?php if (config('workshop.allow_sockets') && $item->getDefinitions()->hasSockets()): ?>
                <h2 class="title"><strong><?= __('Socket options') ?></strong></h2>

                <?php for ($i = 0; $i < $item->getDefinitions()->getMaxSockets(); $i++): ?>
                    <?php $socket = $item->getSocket($i) ?>
                    <label class="form-control-label" for="item-socket-<?= $i ?>"><?= __('Socket #%d', $i+1) ?></label>
                    <select class="form-control" data-default="<?= $socket->get() ?>" data-prices="<?= $prices['socket'] ?>" id="item-socket-<?= $i ?>" name="socket[<?= $i ?>]" style="width:100%">
                        <option<?= $socket->isNull() ? ' selected' : '' ?>  value="-2"><?= __('No socket') ?></option>
                        <option<?= $socket->isEmpty() ? ' selected' : '' ?> value="-1"><?= __('Empty socket') ?></option>
                        <?php if (config('workshop.allow_sockets', 0) == 1): ?>
                            <?php foreach ($item->getDefinitions()->getSockets() as $type => $socks):  ?>
                                <optgroup label="<?= __($type) ?>">
                                    <?php foreach ($socks as $sock): ?>
                                        <option<?= $socket->get() === $sock['value'] ? ' selected' : '' ?> value="<?= $sock['value'] ?>"><?= $sock['name'] ?></option>
                                    <?php endforeach ?>
                                </optgroup>
                            <?php endforeach ?>
                        <?php else: ?>
                            <?php if ($socket->hasValue()): ?>
                                <option selected value="<?= $socket->get() ?>"><?= $socket->getName() ?></option>
                            <?php endif ?>
                        <?php endif ?>
                    </select>
                <?php endfor ?>
            <?php endif ?>

            <?php if (config('workshop.allow_mastery', 0) && !empty($item->getDefinitions()->getMasteryOptions())): ?>
                <h2 class="title"><strong><?= __('Mastery Options') ?></strong></h2>

                <?php foreach ($item->getDefinitions()->getMasteryOptions() as $index => $mastery): ?>
                    <div class="check">
                        <input class="styled-checkbox"<?= $item->getExcellent($index) ? ' checked' : '' ?> data-default="<?= $item->getExcellent($index) ? 1 : 0 ?>" data-prices="<?= $prices['excellent'] ?>" type="checkbox" id="item-excellent-<?= $index ?>" value="1" name="excellent[<?= $index ?>]" />
                        <label for="item-excellent-<?= $index ?>"><?= $name ?></label>
                    </div>
                <?php endforeach ?>
            <?php endif ?>

            <?php if (config('workshop.allow_mastery_bonus', 0) && $item->getMasteryBonus()->exists()): ?>
                <h2 class="title mt-3"><strong><?= __('Mastery Bonus') ?></strong></h2>

                <div class="form-group">
                    <select class="form-control" data-default="<?= $item->getMasteryBonus()->get() ?>" data-prices="<?= $prices['mastery_bonus'] ?? 0 ?>" id="item-mastery-bonus" name="mastery_bonus" style="width:100%">
                        <option value=""></option>
                        <?php foreach ($item->getMasteryBonus()->available() as $index => $name):  ?>
                            <option<?= $item->getMasteryBonus()->get() === $index ? ' selected' : '' ?> value="<?= $index ?>"><?= $name ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            <?php endif ?>
        </div>

        <div class="workshop-upgrade-price">
            <h2 class="title"><strong><?= __('Prices') ?></strong></h2>
            <?php foreach (config('workshop.coins', []) as $coin): ?>
                <div class="price">
                    <input class="styled-radio" type="radio" id="price-<?= $coin ?>" name="coin" value="<?= $coin ?>" />
                    <label for="price-<?= $coin ?>"><span id="total-<?= $coin ?>">0</span> <?= util('Coin')->name($coin) ?></label>
                </div>
            <?php endforeach ?>
        </div>

        <div class="submit">
            <input type="submit" class="btn btn-info" value="<?= __('Upgrade') ?>" />
        </div>
    </form>
<?php endif ?>