<?= partial('rates') ?>

<form data-ajax action="<?= url_to('/panel/account/exchange') ?>" class="form" method="post">
    <div class="box-panel">
        <div class="box-panel-title"><?= __('Exchange') ?></div>
        <div class="box-panel-content">
            <div class="box">
                <div class="row">
                    <div style="width:39%;margin-right:1%;float:left">
                        <label for="coin-amount"><?= __('Amount') ?></label>
                        <input style="width:100%" id="coin-amount" class="calculate-rate" type="text" name="amount" />
                    </div>
                    <div style="width:60%;float:left">
                        <label for="coin-from"><?= __('Coin') ?></label>
                        <select style="width:100%" id="coin-from" class="calculate-rate" name="from">
                            <option value=""></option>
                            <?php foreach ($coins as $id => $coin): ?>
                                <option value="<?= $id ?>"><?= util('Coin')->name($id) ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="row" style="text-align:center;line-height:30px;font-size:18px;"><?= __('To') ?></div>
                <div class="row">
                    <select id="coin-to" class="calculate-rate" name="to" style="width:100%">
                        <option value=""></option>
                    </select>
                </div>
                <div class="row" style="text-align:center;line-height:30px;font-size:18px;">=</div>
                <div class="row">
                    <div id="change-tax-text" class="align-center" style="display:none"><?= __('Tax') ?></div>
                    <div id="change-tax" class="align-center" style="font-size:20px"></div>
                    <div id="change-amount-text" class="align-center" style="display:none;margin-top:10px"><?= __('You receive') ?></div>
                    <div id="change-amount" class="align-center" style="font-size:20px"></div>
                </div>
            </div>

        </div>
        <div class="submit">
            <input type="submit" class="btn" value="<?= __('Convert') ?>">
        </div>
    </div>
</form>