<section class="content-header">
    <h1><?= __('Edit poll') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/polls') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">

    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#"><?= __('Poll') ?></a></li>
            <li><a data-ajax href="<?= url_to('/admin/polls/answers?poll_id=' . $poll['id']) ?>"><?= __('Answers') ?></a></li>
        </ul>
        <div class="tab-content">
            <form data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/polls/edit/' . $poll['id']) ?>" method="post">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-title"><?= __('Title') ?> <span class="required">*</span></label>

                    <div class="col-sm-5">
                        <input class="form-control" value="<?= $poll['title'] ?>" type="text" name="title" id="poll-title" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-starts-at"><?= __('Starts at') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <input data-show-calendar class="form-control" value="<?= util('Date')->date($poll['start_date']) ?>" type="text" name="start_at" id="poll-starts-at" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-ends-at"><?= __('Ends at') ?></label>

                    <div class="col-sm-3">
                        <input data-show-calendar class="form-control" value="<?= empty($poll['end_date']) ? '' : util('Date')->date($poll['end_date']) ?>" type="text" name="end_at" id="poll-end-at" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-multiple"><?= __('Allow multiple') ?></label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input<?= $poll['allow_multiple'] ? ' checked' : '' ?> class="form-control" type="checkbox" id="poll-multiple" value="1" name="multiple" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-allow-ips"><?= __('Allow IPs') ?></label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input<?= $poll['allow_ips'] ? ' checked' : '' ?> class="form-control" type="checkbox" id="poll-allow-ips" value="1" name="allow_ips" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-only-logged-in"><?= __('Only logged in') ?></label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input<?= $poll['only_logged_in'] ? ' checked' : '' ?> class="form-control" type="checkbox" id="poll-only-logged-in" value="1" name="only_logged_in" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="poll-active"><?= __('Active') ?></label>

                    <div class="col-sm-8" style="padding-top:5px">
                        <input<?= $poll['active'] ? ' checked' : '' ?> class="form-control" type="checkbox" id="poll-active" value="1" name="active" />
                    </div>
                </div>

                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </form>
        </div>
    </div>
</section>