<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Coins') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <ul class="breadcrumber">
        <li><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
        <li class="active"><?= __('Coins') ?></li>
    </ul>
</div>