<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('Trackers') ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item"><a href="<?= url_to('/my-trackers') ?>" data-ajax><?= __('My trackers') ?></a></li>
            <li cloass="breadcrumb-item active"><?= __('Add') ?></li>
        </ol>
    </nav>

    <form data-ajax data-upload action="<?= url_to('/my-trackers/add') ?>" enctype="multipart/form-data" method="POST" class="form form-action">
        <?= function_exists('csrf_field') ? csrf_field() : '' ?>

        <div class="form-group">
            <label for="title"><?= __('Title') ?> <span class="required">*</span></label>

            <input type="text" class="form-control" style="width:100%" name="title" id="title" />
        </div>

        <div class="form-group">
            <label for="category"><?= __('Category') ?> <span class="required">*</span></label>

            <select name="category_id" class="form-control" id="category">
                <option value=""></option>
                <?php foreach ($categories as $category): ?>
                    <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="form-group">
            <label for="frequency"><?= __('Frequency') ?></label>

            <select name="frequency" class="form-control" id="frequency">
                <?php foreach ($frequencies as $key => $value): ?>
                    <option value="<?= $key ?>"><?= $value ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="form-group">
            <label for="system"><?= __('Operation system') ?></label>

            <select name="system" class="form-control" id="system">
                <?php foreach ($systems as $system): ?>
                    <option value="<?= $system ?>"><?= $system ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="form-group">
            <label for="images"><?= __('Images') ?></label>

            <input data-upload-field class="form-control-file" type="file" multiple name="images" id="images" />
        </div>

        <div class="form-group">
            <label for="description"><?= __('Description') ?> <span class="required">*</span></label>

            <textarea name="description" class="form-control" id="description"></textarea>
        </div>

        <div class="form-group">
            <label for="reproduce"><?= __('How to reproduce') ?> <span class="required">*</span></label>

            <textarea name="reproduce" class="form-control" id="reproduce"></textarea>
        </div>

        <div class="submit">
            <input type="submit" value="<?= __('Open tracker') ?>" class="btn btn-info" />
        </div>
    </form>
</div>