<section class="content-header">
    <h1><?= __('Add new service') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/services') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">
    <div class="box box-default">
        <form data-ajax class="form-horizontal" action="<?= url_to('/admin/services/add') ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="service-name"><?= __('Name') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <input class="form-control" type="text" name="name" id="service-name" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="service-service"><?= __('Service') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <input class="form-control" type="text" name="service" id="service-service" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="service-url">URL</label>

                    <div class="col-sm-4">
                        <input class="form-control" type="text" name="url" id="service-url" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="service-parent_id"><?= __('Parent service') ?></label>

                    <div class="col-sm-3">
                        <select class="form-control" name="parent_id" id="service-parent_id">
                            <option value=""></option>
                            <?php foreach ($services as $service): ?>
                                <option value="<?= $service['id'] ?>"><?= $service['name'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="service-allowed"><?= __('Free for all') ?>?</label>

                    <div class="col-sm-10" style="padding-top:5px">
                        <input class="form-control" type="checkbox" id="service-allowed" value="1" name="allowed" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label"><?= __('Vip') ?></label>

                    <div class="col-sm-10" style="padding-top:5px;">
                        <?php foreach (config('vip.types', []) as $id => $name): ?>
                            <div style="width:20%;float:left">
                                <input type="checkbox" id="services-vip<?= $id ?>" name="viptype[<?= $id ?>]" /> <label style="vertical-align:-2px;padding-left:5px;" for="services-vip<?= $id ?>"><?= $name ?></label>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="service-active"><?= __('Active') ?>?</label>

                    <div class="col-sm-10" style="padding-top:5px">
                        <input class="form-control" type="checkbox" id="service-active" value="1" name="active" />
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>