<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">Categorias de Eventos</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="row m-b-30">
                <div class="col-sm-6">
                    <a href="/admin/events/categories/add" class="btn btn-primary waves-effect waves-light">Nova Categoria</a>
                    <a href="/admin/events" class="btn btn-default waves-effect waves-light">Voltar para Eventos</a>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-hover mails m-0 table table-actions-bar">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome da Categoria</th>
                            <th style="min-width: 90px;"><?= __("Actions") ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (empty($categories)): ?>
                            <tr><td colspan="3" class="text-center">Nenhuma categoria encontrada</td></tr>
                        <?php else: ?>
                            <?php foreach ($categories as $category): ?>
                                <tr>
                                    <td><?= $category["id"] ?></td>
                                    <td><?= $category["name"] ?></td>
                                    <td>
                                        <a href="/admin/events/categories/edit/<?= $category["id"] ?>" class="table-action-btn"><i class="md md-edit"></i></a>
                                        <a href="/admin/events/categories/delete/<?= $category["id"] ?>" class="table-action-btn delete-button"><i class="md md-close"></i></a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>