<div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
        <span class="info-box-icon bg-blue"><i class="fa fa-ticket"></i></span>
        <div class="info-box-content">
            <span class="info-box-text"><?= __('Pending tickets') ?></span>
            <span class="info-box-number"><a data-ajax href="<?= url_to('/admin/helpdesk/tickets/pending') ?>"><?= util('Number')->format($pendings) ?></a></span>
            <span class="info-box-text"><?= __('Tickets in progress') ?></span>
            <span class="info-box-number"><a data-ajax href="<?= url_to('/admin/helpdesk/tickets/waiting') ?>"><?= util('Number')->format($waitings) ?></a></span>
        </div>
    </div>
</div>