<section class="content-header">
    <h1><?= __('Search results') ?></h1>
</section>

<section class="content">
    <?php if (empty($accounts)): ?>
        <div class="callout callout-warning">
            <h4>Ops!</h4>
            <p><?= __('No account found') ?></p>
        </div>
    <?php else: ?>
        <div class="box box-default">
            <table class="table table-condensed table-hover table-striped">
                <thead>
                    <tr>
                        <th width="120"><?= __('Account') ?></th>
                        <th><?= __('Characters') ?></th>
                        <th><?= __('Email') ?></th>
                        <th>IP</th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach ($accounts as $account): ?>
                        <tr<?= $account['blocked'] ? ' class="error"' : '' ?>>
                            <td><a data-ajax href="<?= url_to('/admin/accounts/edit/' . $account['username']) ?>"><?= $account['username'] ?></a></td>
                            <td>
                                <?php foreach ($account['characters'] as $key => $character): ?>
                                    <a data-ajax href="<?= url_to('/admin/characters/edit/' . $character['name']) ?>"><?= $character['name'] ?></a><?= $key + 1 < count($account['characters']) ? ', ' : '' ?>
                                <?php endforeach ?>
                            </td>
                            <td><?= $account['email'] ?></td>
                            <td><?= $account['ip'] ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    <?php endif ?>
</section>