<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?= __('Logs') ?></h3>
</div>

<table class="table table-condensed table-hover table-striped">
    <thead>
    <tr>
        <th width="120"><?= __('Date') ?></th>
        <th><?= __('Log') ?></th>
        <th width="80"><?= __('Type') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($logs as $log): ?>
        <tr>
            <td><?= util('Date')->dateTime($log['create_date']) ?></td>
            <td><?= $log['log'] ?></td>
            <td><?= $log['type'] ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>