<section class="content-header">
    <h1><?= __('Add new user') ?></h1>

    <div class="actions">
        <a data-ajax class="btn btn-default btn-sm" href="<?= url_to('/admin/users') ?>"><?= __('List') ?></a>
    </div>
</section>

<section class="content">

    <div class="box box-default">
        <form data-ajax class="form-horizontal form-focus" action="<?= url_to('/admin/users/add') ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="user-name"><?= __('Name') ?> <span class="required">*</span></label>

                    <div class="col-sm-4">
                        <input class="form-control" type="text" name="name" id="user-name" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="user-email"><?= __('Email') ?></label>

                    <div class="col-sm-5">
                        <input class="form-control" type="text" name="email" id="user-email" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="user-username"><?= __('Username') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <input class="form-control" type="text" name="username" id="user-username" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="user-password"><?= __('Password') ?> <span class="required">*</span></label>

                    <div class="col-sm-3">
                        <input class="form-control" value="" type="password" name="password" id="user-password" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="user-super-user"><?= __('Super user') ?>?</label>

                    <div class="col-sm-10" style="padding-top:5px">
                        <input class="form-control" type="checkbox" id="user-super-user" value="1" name="super_user" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="user-group"><?= __('Group') ?></label>

                    <div class="col-sm-3">
                        <select class="form-control" name="group_id" id="user-group">
                            <?php foreach ($groups as $group): ?>
                                <option value="<?= $group['id'] ?>"><?= $group['name'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-sm-offset-2" style="padding-left:5px">
                    <input type="submit" class="btn btn-primary" value="<?= __('Save') ?>" />
                </div>
            </div>
        </form>
    </div>
</section>