		<form action="<?= url_to('/admin/login') ?>" method="post">
<?php if (isset($error)): ?>
            <center><font color="#FFF"><?= $error ?></font>
        <?php endif ?></center><br>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" name="username" class="form-control" placeholder="Usuario"id="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" name="password" class="form-control" placeholder="Senha" value="" type="password" id="password">
					</div>
					
					<div class="form-group">
						<input type="submit" class="btn float-right login_btn"value="ACESSAR">
					</div><br><br><br><br><br>
					
				 </form>
				 <br> <br>
<center><font color="#FFF"> © Designer Joao Lima</center></font>