<div class="box-panel">
    <div class="box-panel-title">
        <div class="box-panel-title-left"></div>
        <div class="box-panel-title-content"><?= __('My purchases in market') ?></div>
        <div class="box-panel-title-right"></div>
    </div>
    <div class="box-panel-content">
        <table class="list">
            <thead>
                <tr>
                    <th><?= __('Item') ?></th>
                    <th style="text-align:center" width="90"><?= __('Bought at') ?></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($items as $item): ?>
                    <tr>
                        <td><?= util('Item')->getFullName($item['item']) ?></td>
                        <td style="text-align:center"><?= util('Date')->date($item['bought_date']) ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>