<div class="page-container">
    <div class="page-title">
        <div class="t1">

        </div>
        <div class="t2">
            <h1><?= __('character') ?> <?= $guild->getName() ?></h1>
        </div>
        <div class="t3">

        </div>
    </div>

    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?= url_to('/') ?>" data-ajax><?= __('Home') ?></a></li>
            <li class="breadcrumb-item active"><?= __('Guild perfil') ?></li>
        </ol>
    </nav>

    <h2 class="title"><?= __('information') ?></h2>
    <table class="table table-sm">
        <tr>
            <td valign="top" rowspan="7" width="80">
                <?= util('Guild')->logo($guild->getMark(), 80) ?>
            </td>
            <td width="100"><?= __('guild') ?></td>
            <td><a data-ajax href="<?= url_to('/perfil/guild/' . $guild->getName()) ?>"><?= $guild->getName() ?></a></td>
        </tr>
        <tr>
            <td><?= __('master') ?></td>
            <td><a data-ajax href="<?= url_to('/perfil/character/' . $guild->getMaster()->getName()) ?>"><?= $guild->getMaster()->getName() ?></a></td>
        </tr>
        <tr>
            <td><?= __('score') ?></td>
            <td><?= $guild->getScore() ?></td>
        </tr>
        <tr>
            <td><?= __('members') ?></td>
            <td><?= count($guild->getMembers()) ?></td>
        </tr>
    </table>

    <h2 class="title"><?= __('members') ?></h2>
    <table class="table table-sm table-hover table-striped">
        <thead class="thead-dark">
            <tr>
                <th><?= __('character') ?></th>
                <th><?= __('class') ?></th>
                <?php if (config('columns.resets')): ?>
                    <th><?= __('resets') ?></th>
                <?php endif ?>
                <th><?= __('level') ?></th>
                <th width="50"><?= __('member level') ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($guild->getMembers() as $member): ?>
                <tr>
                    <td><a href="<?= url_to('/perfil/character/' . $member->getName()) ?>" data-ajax><?= $member->getName() ?></a></td>
                    <td><?= util('Character')->className($member->getClass()) ?></td>
                    <?php if (config('columns.resets')): ?>
                        <td><?= $member->getResets() ?></td>
                    <?php endif ?>
                    <td><?= $member->getLevel() ?></td>
                    <td><?= $member->isMaster() ? 'Master' : 'Membro' ?></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>